webtalk_init -webtalk_dir C:/SPB_Data/openwifi-hw/ip/tx_intf/tx_intf/tx_intf.sim/sim_1/behav/xsim/xsim.dir/tx_intf_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Jul 26 13:21:36 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1faa99c9-a530-4681-9c40-69341e7c431d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "663df2bbe41f41c68cf34f68f7dd1632" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 5600H with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3294 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key SystemVerilog -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key File_Counter -value "18" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "455 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "147 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "3799" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "299" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "20.30_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "204948_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2123347957 -regid "" -xml C:/SPB_Data/openwifi-hw/ip/tx_intf/tx_intf/tx_intf.sim/sim_1/behav/xsim/xsim.dir/tx_intf_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/SPB_Data/openwifi-hw/ip/tx_intf/tx_intf/tx_intf.sim/sim_1/behav/xsim/xsim.dir/tx_intf_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/SPB_Data/openwifi-hw/ip/tx_intf/tx_intf/tx_intf.sim/sim_1/behav/xsim/xsim.dir/tx_intf_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
