# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/ASUS/Downloads/Openofdm/openofdm-dot11zynq/Wifi/ip_repo/div_for_rotafft/div_for_rotafft.xci
# IP: The module: 'div_for_rotafft' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ASUS/Downloads/Openofdm/openofdm-dot11zynq/Wifi/ip_repo/div_for_rotafft/div_for_rotafft_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'div_for_rotafft'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/ASUS/Downloads/Openofdm/openofdm-dot11zynq/Wifi/ip_repo/div_for_rotafft/div_for_rotafft.xci
# IP: The module: 'div_for_rotafft' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ASUS/Downloads/Openofdm/openofdm-dot11zynq/Wifi/ip_repo/div_for_rotafft/div_for_rotafft_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'div_for_rotafft'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
