# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/ASUS/Downloads/Openofdm/openofdm-dot11zynq/Wifi/ip_repo/div_gen_csi_over_nova/div_gen_csi_over_nova.xci
# IP: The module: 'div_gen_csi_over_nova' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ASUS/Downloads/Openofdm/openofdm-dot11zynq/Wifi/ip_repo/div_gen_csi_over_nova/div_gen_csi_over_nova_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'div_gen_csi_over_nova'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/ASUS/Downloads/Openofdm/openofdm-dot11zynq/Wifi/ip_repo/div_gen_csi_over_nova/div_gen_csi_over_nova.xci
# IP: The module: 'div_gen_csi_over_nova' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ASUS/Downloads/Openofdm/openofdm-dot11zynq/Wifi/ip_repo/div_gen_csi_over_nova/div_gen_csi_over_nova_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'div_gen_csi_over_nova'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
